%YAML 1.2
---
samples: [ 'test' ]
# number of threads to use throughout pipeline
# if not used then use number of cores
threads: 8

# default quality is 20,20
# uncomment to change quality trim
qual: 20
minlength: 75

mashdb: ['db/RefSeq88n.msh']
qa: [ 'fastp' ]
covs: [ '150' ]

pairs: ['1', '2']

genome_size: 0
